development:
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  database: niceglass_development
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  database: niceglass_test
  pool: 5
  timeout: 5000


production:
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  database: niceglass_production
  pool: 5
  timeout: 5000
